apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: sample-app
      tier: app
  template:
    metadata:
      labels:
        app: sample-app
        tier: app
    spec:
      containers:
      - name: app
        image: mahendrshinde/api-app
        env:
          - name: DBURL
            valueFrom:
              secretKeyRef:
                key: MYSQL_URL
                name: dbconfig        
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                key: MYSQL_USER    
                name: dbconfig
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: dbconfig
          - name: DBNAME
            valueFrom:
              secretKeyRef:
                key: MYSQL_DATABASE   
                name: dbconfig
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
